GitHub Actions:
- changed-files:
  - any-glob-to-any-file: '.github/**/*'

tests:
- changed-files:
  - any-glob-to-any-file: 'tests/**/*'

database:
- changed-files:  
  - any-glob-to-any-file: 'db/**/*'

api:
- changed-files:  
  - any-glob-to-any-file: 'folksonomy/api.py'

models:
- changed-files:  
  - any-glob-to-any-file: 'folksonomy/models.py'

dependancies:
- changed-files:  
  - any-glob-to-any-file: 'folksonomy/dependencies.py'
