# Docker Compose configuration for Folksonomy API
services:
  folksonomy_api :
    image: ghcr.io/openfoodfacts/folksonomy-api:${TAG}
    restart: ${RESTART_POLICY:-always}
    ports:
      - "${API_EXPOSE:-127.0.0.1:8000}:8000"
    volumes:
      # Mount .env file for environment variables
      - ./.env:/app/.env
      # Mount a volume for logs
      - api_logs:/app/logs
    env_file:
      - .env
    depends_on:
      folksonomy_db:
        condition: service_healthy  # Wait for DB to be fully ready
    networks:
      - default
      - common_net


  folksonomy_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-folksonomy}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-folksonomy}
      - POSTGRES_DB=${POSTGRES_DATABASE:-folksonomy}
    ports:
      - "${DB_EXPOSE:-127.0.0.1:5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-folksonomy} -d ${POSTGRES_DATABASE:-folksonomy}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: ${RESTART_POLICY:-no}
    networks:
      - default

volumes:
  postgres_data:
  api_logs:

# shared local network with Open Food Facts to be able to use local instance
networks:
  common_net:
    name: ${COMMON_NET_NAME}
    external: true
