# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    #if: ${{ github.repository_owner == 'openfoodfacts' }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # ratchet:actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
