 name: Run release-please
 on:
   push:
     branches:
       - main

 jobs:
   release-please:
     if: github.event.repository.fork == false
     runs-on: ubuntu-latest
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v4
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: simple
